grant select on QLBV_DBA.NHANVIEN to THANHTRA, CSYT, YSBS, NGHIENCUU;
grant select on QLBV_DBA.BENHNHAN to THANHTRA, YSBS, BENHNHAN;
grant select on QLBV_DBA.HSBA to THANHTRA, CSYT, YSBS, NGHIENCUU, BENHNHAN;
grant select on QLBV_DBA.HSBA_DV to THANHTRA, CSYT, YSBS, NGHIENCUU, BENHNHAN;
grant select on QLBV_DBA.CSYT to THANHTRA, CSYT, YSBS, NGHIENCUU, BENHNHAN;
grant select on QLBV_DBA.KHOA to THANHTRA, CSYT, YSBS, NGHIENCUU, BENHNHAN;
grant select on QLBV_DBA.DICHVU to THANHTRA, CSYT, YSBS, NGHIENCUU, BENHNHAN;

GRANT UPDATE(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT) ON QLBV_DBA.NHANVIEN TO THANHTRA, CSYT, YSBS, NGHIENCUU;
GRANT UPDATE(TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON QLBV_DBA.BENHNHAN TO BENHNHAN;

GRANT INSERT, DELETE ON QLBV_DBA.HSBA TO CSYT;
GRANT INSERT, DELETE ON QLBV_DBA.HSBA_DV TO CSYT;